CREATE TABLE IF NOT EXISTS dataset_logs (
    id SERIAL PRIMARY KEY,
    ref VARCHAR(512) UNIQUE NOT NULL,
    title VARCHAR(512),
    path TEXT,
    downloaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prediction_logs (
    id SERIAL PRIMARY KEY,
    payload JSONB,
    response JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
